# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2a63484c3b50c064c9d0e0a0d10b00d6"
name = "admin"
handle = "admin-64"
application_url = "https://admin-action-block.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
dev_store_url = "codeinspire2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_customers,read_orders,read_payment_customizations,read_products,write_files,write_orders,write_payment_customizations,write_pixels,write_products"

[auth]
redirect_urls = [
  "https://admin-action-block.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
