# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a98e00674e00da851db776a56ac3150d"
name = "suite-development"
handle = "admin-action-block-1"
application_url = "https://admin-action-block--development.gadget.app/"
embedded = true

[build]
dev_store_url = "codeinspire2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_files,read_fulfillments,read_locations,read_orders,read_payment_customizations,read_products,unauthenticated_read_customers,unauthenticated_write_customers,write_assigned_fulfillment_orders,write_customers,write_files,write_orders,write_payment_customizations,write_pixels,write_products,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders,write_fulfillments,read_merchant_managed_fulfillment_orders,read_assigned_fulfillment_orders,read_third_party_fulfillment_orders,read_order_edits,write_order_edits"

[auth]
redirect_urls = [
  "https://admin-action-block--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false